# Overview of Pandas for Data Processing

Let us get an overview of Python Pandas Library.
- Pandas is one of the most popular libraries of Python.
- Usage: Data Processing, Data Analysis (including Visualization)
- Robust APIs to read data from different sources, process data and write data to different targets.
- Integrated with File Formats, Databases, REST APIs, etc
- Easy to integrate with additional File Systems or Databases (install additional libraries)

In [2]:
# pip install pandas

# Use above command if pandas not already installed on your computer

In [2]:
import pandas as pd

In [ ]:
pd.read_csv('data/retail_db/orders/part-00000')

# Will create a dataframe. Since column names are not defined, it will take first row as header

           1  2013-07-25 00:00:00.0  11599           CLOSED
0          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
1          3  2013-07-25 00:00:00.0  12111         COMPLETE
2          4  2013-07-25 00:00:00.0   8827           CLOSED
3          5  2013-07-25 00:00:00.0  11318         COMPLETE
4          6  2013-07-25 00:00:00.0   7130         COMPLETE
...      ...                    ...    ...              ...
68877  68879  2014-07-09 00:00:00.0    778         COMPLETE
68878  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68879  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68880  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68881  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68882 rows x 4 columns]

In [ ]:
pd.read_csv('data/retail_db/orders/part-00000',header=None)

# Now it wont consider first row as header

           0                      1      2                3
0          1  2013-07-25 00:00:00.0  11599           CLOSED
1          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
2          3  2013-07-25 00:00:00.0  12111         COMPLETE
3          4  2013-07-25 00:00:00.0   8827           CLOSED
4          5  2013-07-25 00:00:00.0  11318         COMPLETE
...      ...                    ...    ...              ...
68878  68879  2014-07-09 00:00:00.0    778         COMPLETE
68879  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68880  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68881  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68882  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68883 rows x 4 columns]

In [4]:
orders_columns = ['order_id', 'order_date','order_customer_id', 'order_status']

In [5]:
pd.read_csv('data/retail_db/orders/part-00000',names=orders_columns)

# Will have appropriate column names

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [6]:
orders = pd.read_csv('data/retail_db/orders/part-00000',names=orders_columns)

In [7]:
orders

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [ ]:
orders.columns

# Returns all the column names in the orders dataframe

Index(['order_id', 'order_date', 'order_customer_id', 'order_status'], dtype='str')

In [ ]:
orders['order_status'].unique()

# Returns all the unique values in order_status column

<StringArray>
[         'CLOSED', 'PENDING_PAYMENT',        'COMPLETE',      'PROCESSING',
  'PAYMENT_REVIEW',         'PENDING',         'ON_HOLD',        'CANCELED',
 'SUSPECTED_FRAUD']
Length: 9, dtype: str

In [10]:
orders.query("order_status == 'COMPLETE'")

# Returns all the entries where order_status is COMPLETE

       order_id             order_date  order_customer_id order_status
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
6             7  2013-07-25 00:00:00.0               4530     COMPLETE
14           15  2013-07-25 00:00:00.0               2568     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[22899 rows x 4 columns]

In [ ]:
orders.query("order_status == 'COMPLETE' and order_date == '2014-07-06 00:00:00.0'")

# Returns entries with COMPLETE status and specified order date

       order_id             order_date  order_customer_id order_status
54748     54749  2014-07-06 00:00:00.0               6099     COMPLETE
54755     54756  2014-07-06 00:00:00.0              10001     COMPLETE
54760     54761  2014-07-06 00:00:00.0               2366     COMPLETE
54761     54762  2014-07-06 00:00:00.0               5642     COMPLETE
54762     54763  2014-07-06 00:00:00.0               9814     COMPLETE
54763     54764  2014-07-06 00:00:00.0               3496     COMPLETE
54770     54771  2014-07-06 00:00:00.0              10715     COMPLETE
54771     54772  2014-07-06 00:00:00.0               1783     COMPLETE
54773     54774  2014-07-06 00:00:00.0               4355     COMPLETE
54781     54782  2014-07-06 00:00:00.0               7296     COMPLETE
54786     54787  2014-07-06 00:00:00.0               6492     COMPLETE
54791     54792  2014-07-06 00:00:00.0                648     COMPLETE
54792     54793  2014-07-06 00:00:00.0               6318     COMPLETE
54794     54795  2014-07-06 00:00:00.0                749     COMPLETE
54801     54802  2014-07-06 00:00:00.0              11576     COMPLETE
54806     54807  2014-07-06 00:00:00.0               6539     COMPLETE
54811     54812  2014-07-06 00:00:00.0               8958     COMPLETE
54812     54813  2014-07-06 00:00:00.0               8102     COMPLETE
66898     66899  2014-07-06 00:00:00.0               2999     COMPLETE
66900     66901  2014-07-06 00:00:00.0               3475     COMPLETE
66906     66907  2014-07-06 00:00:00.0               9473     COMPLETE
66914     66915  2014-07-06 00:00:00.0               5324     COMPLETE
66916     66917  2014-07-06 00:00:00.0               1172     COMPLETE
66918     66919  2014-07-06 00:00:00.0               4599     COMPLETE
66920     66921  2014-07-06 00:00:00.0               2308     COMPLETE
66924     66925  2014-07-06 00:00:00.0               4922     COMPLETE
66926     66927  2014-07-06 00:00:00.0              11983     COMPLETE
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE

In [13]:
orders.query("order_status == 'COMPLETE' or order_status == 'CLOSED'")

# Returns entries with either COMPLETE or CLOSED status

# This statement can also be written as:
# orders.query("order_status == ('COMPLETE','CLOSED')")

       order_id             order_date  order_customer_id order_status
0             1  2013-07-25 00:00:00.0              11599       CLOSED
2             3  2013-07-25 00:00:00.0              12111     COMPLETE
3             4  2013-07-25 00:00:00.0               8827       CLOSED
4             5  2013-07-25 00:00:00.0              11318     COMPLETE
5             6  2013-07-25 00:00:00.0               7130     COMPLETE
...         ...                    ...                ...          ...
68875     68876  2014-07-06 00:00:00.0               4124     COMPLETE
68877     68878  2014-07-08 00:00:00.0               6753     COMPLETE
68878     68879  2014-07-09 00:00:00.0                778     COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117     COMPLETE
68882     68883  2014-07-23 00:00:00.0               5533     COMPLETE

[30455 rows x 4 columns]