# Overview of Pandas for Data Processing

Let us get an overview of Python Pandas Library.
- Pandas is one of the most popular libraries of Python.
- Usage: Data Processing, Data Analysis (including Visualization)
- Robust APIs to read data from different sources, process data and write data to different targets.
- Integrated with File Formats, Databases, REST APIs, etc
- Easy to integrate with additional File Systems or Databases (install additional libraries)

In [2]:
# pip install pandas

# Use above command if pandas not already installed on your computer

In [3]:
import pandas as pd

In [ ]:
pd.read_csv('data/retail_db/orders/part-00000')

# Will create a dataframe. Since column names are not defined, it will take first row as header

           1  2013-07-25 00:00:00.0  11599           CLOSED
0          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
1          3  2013-07-25 00:00:00.0  12111         COMPLETE
2          4  2013-07-25 00:00:00.0   8827           CLOSED
3          5  2013-07-25 00:00:00.0  11318         COMPLETE
4          6  2013-07-25 00:00:00.0   7130         COMPLETE
...      ...                    ...    ...              ...
68877  68879  2014-07-09 00:00:00.0    778         COMPLETE
68878  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68879  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68880  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68881  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68882 rows x 4 columns]

In [ ]:
pd.read_csv('data/retail_db/orders/part-00000',header=None)

# Now it wont consider first row as header

           0                      1      2                3
0          1  2013-07-25 00:00:00.0  11599           CLOSED
1          2  2013-07-25 00:00:00.0    256  PENDING_PAYMENT
2          3  2013-07-25 00:00:00.0  12111         COMPLETE
3          4  2013-07-25 00:00:00.0   8827           CLOSED
4          5  2013-07-25 00:00:00.0  11318         COMPLETE
...      ...                    ...    ...              ...
68878  68879  2014-07-09 00:00:00.0    778         COMPLETE
68879  68880  2014-07-13 00:00:00.0   1117         COMPLETE
68880  68881  2014-07-19 00:00:00.0   2518  PENDING_PAYMENT
68881  68882  2014-07-22 00:00:00.0  10000          ON_HOLD
68882  68883  2014-07-23 00:00:00.0   5533         COMPLETE

[68883 rows x 4 columns]

In [7]:
orders_columns = ['order_id', 'order_date','order_customer_id', 'order_status']

In [ ]:
pd.read_csv('data/retail_db/orders/part-00000',header=None, names=orders_columns)

# Will have appropriate column names

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]