# Joining Data in Pandas Dataframes

Here are the steps involved in joining data using Pandas Dataframe APIs.

- First, we need to define index for both the dataframes that are supposed to be joined.
- Use join to join the Dataframes based on index. The default join is left, we need to make sure right join is used based on the requirement.

In our case, we will join orders and customers using inner join.

In [1]:
import json

In [2]:
import pandas as pd

In [3]:
# Define a helper function that returns sorted column names for a given table schema.
def get_column_names(schemas, table_name):
    column_details = schemas[table_name]
    columns = sorted(column_details, key = lambda col: col['column_position'])
    return [col['column_name'] for col in columns]

In [4]:
schemas = json.load(open('data/retail_db/schemas.json'))

In [5]:
orders_columns = get_column_names(schemas,'orders')

In [6]:
orders = pd.read_csv('data/retail_db/orders/part-00000',names=orders_columns)

In [7]:
orders

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [8]:
customer_columns = get_column_names(schemas,'customers')

In [9]:
customers = pd.read_csv('data/retail_db/customers/part-00000',names=customer_columns)

In [10]:
customer_columns

['customer_id',
 'customer_fname',
 'customer_lname',
 'customer_email',
 'customer_password',
 'customer_street',
 'customer_city',
 'customer_state',
 'customer_zipcode']

In [11]:
customers

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...,...
12430,12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12431,12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12432,12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12433,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12434,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [12]:
orders_columns

['order_id', 'order_date', 'order_customer_id', 'order_status']

In [13]:
orders

       order_id             order_date  order_customer_id     order_status
0             1  2013-07-25 00:00:00.0              11599           CLOSED
1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2             3  2013-07-25 00:00:00.0              12111         COMPLETE
3             4  2013-07-25 00:00:00.0               8827           CLOSED
4             5  2013-07-25 00:00:00.0              11318         COMPLETE
...         ...                    ...                ...              ...
68878     68879  2014-07-09 00:00:00.0                778         COMPLETE
68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE
68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT
68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD
68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE

[68883 rows x 4 columns]

In [14]:
# Now we need to perform join of 'orders' and 'customers'
# The column used for join: order_customer_id (orders) & customer_id (customers)

In [15]:
customers = customers.set_index('customer_id')
customers

# We must set the column where are performing join as index

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
customer_id,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...
12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [16]:
# Similarly for orders
orders = orders.set_index('order_customer_id')
orders

                   order_id             order_date     order_status
order_customer_id
11599                     1  2013-07-25 00:00:00.0           CLOSED
256                       2  2013-07-25 00:00:00.0  PENDING_PAYMENT
12111                     3  2013-07-25 00:00:00.0         COMPLETE
8827                      4  2013-07-25 00:00:00.0           CLOSED
11318                     5  2013-07-25 00:00:00.0         COMPLETE
...                     ...                    ...              ...
778                   68879  2014-07-09 00:00:00.0         COMPLETE
1117                  68880  2014-07-13 00:00:00.0         COMPLETE
2518                  68881  2014-07-19 00:00:00.0  PENDING_PAYMENT
10000                 68882  2014-07-22 00:00:00.0          ON_HOLD
5533                  68883  2014-07-23 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [17]:
# Now lets join both the dataframes

customer_orders = customers.join(orders, how='inner')

In [18]:
customer_orders

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_status
customer_id,,,,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,22945,2013-12-13 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,15192,2013-10-29 00:00:00.0,PENDING_PAYMENT
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,33865,2014-02-18 00:00:00.0,COMPLETE
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,57963,2013-08-02 00:00:00.0,ON_HOLD
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,67863,2013-11-30 00:00:00.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,42915,2014-04-16 00:00:00.0,COMPLETE
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,51800,2014-06-14 00:00:00.0,ON_HOLD
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,61777,2013-12-26 00:00:00.0,COMPLETE
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,41643,2014-04-08 00:00:00.0,PENDING
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,61629,2013-12-21 00:00:00.0,CANCELED

In [19]:
customers

,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode
customer_id,,,,,,,,
1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521
2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126
3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,725
4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069
5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,725
...,...,...,...,...,...,...,...,...
12431,Mary,Rios,XXXXXXXXX,XXXXXXXXX,1221 Cinder Pines,Kaneohe,HI,96744
12432,Angela,Smith,XXXXXXXXX,XXXXXXXXX,1525 Jagged Barn Highlands,Caguas,PR,725
12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756
12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725
12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483

In [20]:
orders

                   order_id             order_date     order_status
order_customer_id
11599                     1  2013-07-25 00:00:00.0           CLOSED
256                       2  2013-07-25 00:00:00.0  PENDING_PAYMENT
12111                     3  2013-07-25 00:00:00.0         COMPLETE
8827                      4  2013-07-25 00:00:00.0           CLOSED
11318                     5  2013-07-25 00:00:00.0         COMPLETE
...                     ...                    ...              ...
778                   68879  2014-07-09 00:00:00.0         COMPLETE
1117                  68880  2014-07-13 00:00:00.0         COMPLETE
2518                  68881  2014-07-19 00:00:00.0  PENDING_PAYMENT
10000                 68882  2014-07-22 00:00:00.0          ON_HOLD
5533                  68883  2014-07-23 00:00:00.0         COMPLETE

[68883 rows x 3 columns]

In [21]:
customers.shape

(12435, 8)

In [22]:
orders.shape

(68883, 3)

In [23]:
customer_orders.shape

(68883, 11)

The statement `customer_orders = customers.join(orders, how='inner')` performs an inner join between the `customers` and `orders` DataFrames in Pandas, based on their indices. Here's a breakdown of what it does:

### Key Concepts
- **Join in Pandas**: The `join` method combines two DataFrames by matching rows based on their indices (not columns, unless specified). It's similar to SQL joins but operates on DataFrame indices by default.
- **Indices in this context**:
  - The `customers` DataFrame has its index set to `'customer_id'` (from an earlier cell: `customers = customers.set_index('customer_id')`).
  - The `orders` DataFrame has its index set to `'order_customer_id'` (from an earlier cell: `orders = orders.set_index('order_customer_id')`).
  - Since `'order_customer_id'` in `orders` corresponds to `'customer_id'` in `customers` (based on the data schema), the indices represent the same logical key for matching customers to their orders.
- **Inner join (`how='inner'`)**: This keeps only the rows where the index values match in both DataFrames. Rows without a match in either DataFrame are excluded.

### What the Statement Does
1. **Matching criteria**: It matches rows where the index of `customers` (i.e., `customer_id` values) equals the index of `orders` (i.e., `order_customer_id` values).
   - For example, if a customer with `customer_id = 1` has orders, those rows will be combined.
   - If a customer has no orders or an order has no matching customer, those rows are dropped.

2. **Result structure**:
   - The resulting `customer_orders` DataFrame includes:
     - All columns from `customers` (e.g., `customer_fname`, `customer_lname`, etc.).
     - All columns from `orders` (e.g., `order_id`, `order_date`, `order_status`).
   - The index of the result is the index from the left DataFrame (`customers`), which is `customer_id`.
   - Duplicate column names (if any) are handled by Pandas (e.g., suffixes like `_x` and `_y` are added, but in this case, the columns are distinct).

3. **Example behavior**:
   - Suppose `customers` has a row for `customer_id = 1` (e.g., Richard Hernandez).
   - And `orders` has rows where `order_customer_id = 1` (e.g., multiple orders for that customer).
   - The join will create combined rows for each matching order, duplicating the customer info for each order.

4. **Why inner join?**: 
   - It ensures only customers with orders (and orders with valid customers) are included.
   - This is appropriate here since the goal is to analyze customer-order relationships, excluding unmatched data.

### Potential Outcomes
- If there are multiple orders per customer, the result will have multiple rows per customer (one per order).
- The shape of `customer_orders` will be smaller than or equal to the combined shapes of `customers` and `orders`, depending on matches.
- From the notebook, you can check shapes: `customers.shape`, `orders.shape`, and `customer_orders.shape` to see the impact.

If you run this cell and inspect `customer_orders`, you'll see the combined data. If there are issues (e.g., no matches), it might result in an empty DataFrame. Let me know if you need help debugging or modifying the join!

In [24]:
customer_orders.reset_index()

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_status
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,22945,2013-12-13 00:00:00.0,COMPLETE
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,15192,2013-10-29 00:00:00.0,PENDING_PAYMENT
2,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,33865,2014-02-18 00:00:00.0,COMPLETE
3,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,57963,2013-08-02 00:00:00.0,ON_HOLD
4,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,67863,2013-11-30 00:00:00.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...
68878,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,42915,2014-04-16 00:00:00.0,COMPLETE
68879,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,51800,2014-06-14 00:00:00.0,ON_HOLD
68880,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,725,61777,2013-12-26 00:00:00.0,COMPLETE
68881,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,41643,2014-04-08 00:00:00.0,PENDING
68882,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,61629,2013-12-21 00:00:00.0,CANCELED

In [25]:
customer_orders.reset_index().groupby('customer_id')['customer_id'].agg(order_count='count').reset_index()

       customer_id  order_count
0                1            1
1                2            4
2                3            7
3                4            6
4                5            4
...            ...          ...
12400        12431           16
12401        12432           10
12402        12433            4
12403        12434            8
12404        12435            2

[12405 rows x 2 columns]

This Pandas expression counts how many orders each customer has in the `customer_orders` DataFrame.

### Step-by-step

- `customer_orders.reset_index()`
  - Converts the index back into a regular column.
  - In this file, the index is `customer_id`, so after this step `customer_id` becomes a normal column again.

- `.groupby('customer_id')`
  - Groups the rows by `customer_id`.
  - Each group now represents all orders for a single customer.

- `['customer_id']`
  - Selects the `customer_id` column from the grouped data.
  - This is the column used for the aggregation.

- `.agg(order_count='count')`
  - Aggregates each group by counting the number of `customer_id` values.
  - Since each row is one order, this count is effectively the number of orders per customer.
  - The result is a new column named `order_count`.

- `.reset_index()`
  - Turns the grouped index (`customer_id`) back into a normal column.
  - This gives a DataFrame with two columns: `customer_id` and `order_count`.

### Final result

A DataFrame showing:
- `customer_id`
- `order_count`

So it answers: “How many orders does each customer have?”